DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['customers','measurements','orders','workers','customer_ledger','worker_ledger','inventory','invoices','daily_production'] LOOP
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS uid uuid NOT NULL DEFAULT gen_random_uuid()', t);
    EXECUTE format('CREATE UNIQUE INDEX IF NOT EXISTS %I ON public.%I(uid)', t || '_uid_key', t);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
  END LOOP;
END $$;

-- Keep the identity sequence ahead of explicitly supplied business numbers
CREATE OR REPLACE FUNCTION public.bump_id_sequence()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE seq text;
BEGIN
  seq := pg_get_serial_sequence(format('public.%I', TG_TABLE_NAME), 'id');
  IF seq IS NOT NULL THEN
    PERFORM setval(seq, GREATEST((SELECT last_value FROM pg_sequences WHERE schemaname||'.'||sequencename = seq), NEW.id), true);
  END IF;
  RETURN NULL;
END $$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['customers','measurements','orders','workers','customer_ledger','worker_ledger','inventory','invoices','daily_production'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_bump_id ON public.%I', t, t);
    EXECUTE format('CREATE TRIGGER trg_%s_bump_id AFTER INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.bump_id_sequence()', t, t);
  END LOOP;
END $$;

-- Highest number used per table, so a device can hand out the next numbers offline
CREATE OR REPLACE FUNCTION public.business_number_floor()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT jsonb_build_object(
    'customers',(SELECT coalesce(max(id),0) FROM customers),
    'measurements',(SELECT coalesce(max(id),0) FROM measurements),
    'orders',(SELECT coalesce(max(id),0) FROM orders),
    'workers',(SELECT coalesce(max(id),0) FROM workers),
    'customer_ledger',(SELECT coalesce(max(id),0) FROM customer_ledger),
    'worker_ledger',(SELECT coalesce(max(id),0) FROM worker_ledger),
    'inventory',(SELECT coalesce(max(id),0) FROM inventory),
    'invoices',(SELECT coalesce(max(id),0) FROM invoices),
    'daily_production',(SELECT coalesce(max(id),0) FROM daily_production))
$$;
REVOKE ALL ON FUNCTION public.business_number_floor() FROM public, anon;
GRANT EXECUTE ON FUNCTION public.business_number_floor() TO authenticated;
REVOKE ALL ON FUNCTION public.bump_id_sequence() FROM public, anon, authenticated;