-- 1. Deletion markers so other devices learn about deletes
CREATE TABLE IF NOT EXISTS public.sync_tombstones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  row_id bigint NOT NULL,
  row_uid uuid,
  user_id uuid NOT NULL,
  deleted_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.sync_tombstones TO authenticated;
GRANT ALL ON public.sync_tombstones TO service_role;
ALTER TABLE public.sync_tombstones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own select" ON public.sync_tombstones FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS sync_tombstones_user_time ON public.sync_tombstones(user_id, deleted_at);

CREATE OR REPLACE FUNCTION public.record_tombstone()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.sync_tombstones(table_name, row_id, row_uid, user_id)
  VALUES (TG_TABLE_NAME, OLD.id, OLD.uid, OLD.user_id);
  RETURN OLD;
END $$;
REVOKE ALL ON FUNCTION public.record_tombstone() FROM public, anon, authenticated;

-- 2. Stock movement history (stock in / out / adjustment)
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id bigint NOT NULL REFERENCES public.inventory(id),
  kind text NOT NULL DEFAULT 'in',
  qty_change numeric NOT NULL DEFAULT 0,
  note text,
  movement_date date NOT NULL DEFAULT CURRENT_DATE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS stock_movements_uid_key ON public.stock_movements(uid);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_movements TO authenticated;
GRANT ALL ON public.stock_movements TO service_role;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own select" ON public.stock_movements FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "own insert" ON public.stock_movements FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own update" ON public.stock_movements FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own delete" ON public.stock_movements FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TRIGGER trg_stock_movements_updated BEFORE UPDATE ON public.stock_movements FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_stock_movements_bump_id AFTER INSERT ON public.stock_movements FOR EACH ROW EXECUTE FUNCTION public.bump_id_sequence();

-- A movement adjusts the item's quantity in the cloud, so movements from
-- several offline devices add up instead of overwriting each other.
CREATE OR REPLACE FUNCTION public.apply_stock_movement()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.deleted_at IS NULL THEN
    UPDATE public.inventory SET quantity = quantity + NEW.qty_change
    WHERE id = NEW.item_id AND user_id = NEW.user_id;
  ELSIF TG_OP = 'UPDATE' AND OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
    UPDATE public.inventory SET quantity = quantity - OLD.qty_change
    WHERE id = OLD.item_id AND user_id = OLD.user_id;
  ELSIF TG_OP = 'UPDATE' AND OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
    UPDATE public.inventory SET quantity = quantity + NEW.qty_change
    WHERE id = NEW.item_id AND user_id = NEW.user_id;
  END IF;
  RETURN NULL;
END $$;
REVOKE ALL ON FUNCTION public.apply_stock_movement() FROM public, anon, authenticated;
CREATE TRIGGER trg_stock_movements_apply AFTER INSERT OR UPDATE ON public.stock_movements FOR EACH ROW EXECUTE FUNCTION public.apply_stock_movement();

-- 3. Tombstone triggers on every synced table
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['customers','measurements','orders','workers','customer_ledger','worker_ledger','inventory','invoices','daily_production','stock_movements'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_tombstone ON public.%I', t, t);
    EXECUTE format('CREATE TRIGGER trg_%s_tombstone AFTER DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.record_tombstone()', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I(user_id, updated_at)', t || '_user_updated', t);
  END LOOP;
END $$;

-- 4. Number floor also covers stock movements
CREATE OR REPLACE FUNCTION public.business_number_floor()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT jsonb_build_object(
    'customers',(SELECT coalesce(max(id),0) FROM customers),
    'measurements',(SELECT coalesce(max(id),0) FROM measurements),
    'orders',(SELECT coalesce(max(id),0) FROM orders),
    'workers',(SELECT coalesce(max(id),0) FROM workers),
    'customer_ledger',(SELECT coalesce(max(id),0) FROM customer_ledger),
    'worker_ledger',(SELECT coalesce(max(id),0) FROM worker_ledger),
    'inventory',(SELECT coalesce(max(id),0) FROM inventory),
    'invoices',(SELECT coalesce(max(id),0) FROM invoices),
    'daily_production',(SELECT coalesce(max(id),0) FROM daily_production),
    'stock_movements',(SELECT coalesce(max(id),0) FROM stock_movements))
$$;
REVOKE ALL ON FUNCTION public.business_number_floor() FROM public, anon;
GRANT EXECUTE ON FUNCTION public.business_number_floor() TO authenticated;